@startuml

title __ABSTRACTFACTORYMETHOD-EXERCISE's Class Diagram__\n

  namespace es.ull.patrones {
    class Main {
    }
  }
  

  namespace es.ull.patrones {
    namespace es.ull.patrones {
      class es.ull.patrones.Paralell {
      }
    }
  }
  

  namespace es.ull.patrones {
    namespace es.ull.patrones {
      namespace factory {
        class es.ull.patrones.factory.NTFactory {
        }
      }
    }
  }
  

  namespace es.ull.patrones {
    namespace es.ull.patrones {
      namespace factory {
        interface es.ull.patrones.factory.SystemFactory {
        }
      }
    }
  }
  

  namespace es.ull.patrones {
    namespace es.ull.patrones {
      namespace factory {
        class es.ull.patrones.factory.UNIXFactory {
        }
      }
    }
  }
  

  namespace es.ull.patrones {
    namespace es.ull.patrones {
      namespace factory {
        class es.ull.patrones.factory.VMSFactory {
        }
      }
    }
  }
  

  namespace es.ull.patrones {
    namespace es.ull.patrones {
      namespace product.pipeProduct {
        interface es.ull.patrones.product.pipeProduct.Pipe {
        }
      }
    }
  }
  

  namespace es.ull.patrones {
    namespace es.ull.patrones {
      namespace product.pipeProduct {
        class es.ull.patrones.product.pipeProduct.PipeNT {
        }
      }
    }
  }
  

  namespace es.ull.patrones {
    namespace es.ull.patrones {
      namespace product.pipeProduct {
        class es.ull.patrones.product.pipeProduct.PipeUNIX {
        }
      }
    }
  }
  

  namespace es.ull.patrones {
    namespace es.ull.patrones {
      namespace product.pipeProduct {
        class es.ull.patrones.product.pipeProduct.PipeVMS {
        }
      }
    }
  }
  

  namespace es.ull.patrones {
    namespace es.ull.patrones {
      namespace product.socketProduct {
        interface es.ull.patrones.product.socketProduct.Socket {
        }
      }
    }
  }
  

  namespace es.ull.patrones {
    namespace es.ull.patrones {
      namespace product.socketProduct {
        class es.ull.patrones.product.socketProduct.SocketNT {
        }
      }
    }
  }
  

  namespace es.ull.patrones {
    namespace es.ull.patrones {
      namespace product.socketProduct {
        class es.ull.patrones.product.socketProduct.SocketUNIX {
        }
      }
    }
  }
  

  namespace es.ull.patrones {
    namespace es.ull.patrones {
      namespace product.socketProduct {
        class es.ull.patrones.product.socketProduct.SocketVMS {
        }
      }
    }
  }
  

  namespace es.ull.patrones {
    namespace es.ull.patrones {
      namespace product.threadProduct {
        interface es.ull.patrones.product.threadProduct.ThreadI {
        }
      }
    }
  }
  

  namespace es.ull.patrones {
    namespace es.ull.patrones {
      namespace product.threadProduct {
        class es.ull.patrones.product.threadProduct.ThreadNT {
        }
      }
    }
  }
  

  namespace es.ull.patrones {
    namespace es.ull.patrones {
      namespace product.threadProduct {
        class es.ull.patrones.product.threadProduct.ThreadUNIX {
        }
      }
    }
  }
  

  namespace es.ull.patrones {
    namespace es.ull.patrones {
      namespace product.threadProduct {
        class es.ull.patrones.product.threadProduct.ThreadVMS {
        }
      }
    }
  }
  

  es.ull.patrones.Paralell o-- es.ull.patrones.factory.SystemFactory : factory
  es.ull.patrones.factory.NTFactory .up.|> es.ull.patrones.factory.SystemFactory
  es.ull.patrones.factory.UNIXFactory .up.|> es.ull.patrones.factory.SystemFactory
  es.ull.patrones.factory.VMSFactory .up.|> es.ull.patrones.factory.SystemFactory
  es.ull.patrones.product.pipeProduct.PipeNT .up.|> es.ull.patrones.product.pipeProduct.Pipe
  es.ull.patrones.product.pipeProduct.PipeUNIX .up.|> es.ull.patrones.product.pipeProduct.Pipe
  es.ull.patrones.product.pipeProduct.PipeVMS .up.|> es.ull.patrones.product.pipeProduct.Pipe
  es.ull.patrones.product.socketProduct.SocketNT .up.|> es.ull.patrones.product.socketProduct.Socket
  es.ull.patrones.product.socketProduct.SocketUNIX .up.|> es.ull.patrones.product.socketProduct.Socket
  es.ull.patrones.product.socketProduct.SocketVMS .up.|> es.ull.patrones.product.socketProduct.Socket
  es.ull.patrones.product.threadProduct.ThreadNT .up.|> es.ull.patrones.product.threadProduct.ThreadI
  es.ull.patrones.product.threadProduct.ThreadUNIX .up.|> es.ull.patrones.product.threadProduct.ThreadI
  es.ull.patrones.product.threadProduct.ThreadVMS .up.|> es.ull.patrones.product.threadProduct.ThreadI


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
