@startuml

title __FACTORY's Class Diagram__\n

  namespace es.ull.patrones {
    namespace es.ull.patrones {
      namespace factory {
        class es.ull.patrones.factory.NTFactory {
            + createPipe()
            + createSocket()
            + createThread()
            + getNameOfFactory()
        }
      }
    }
  }
  

  namespace es.ull.patrones {
    namespace es.ull.patrones {
      namespace factory {
        interface es.ull.patrones.factory.SystemFactory {
            {abstract} + createPipe()
            {abstract} + createSocket()
            {abstract} + createThread()
            {abstract} + getNameOfFactory()
        }
      }
    }
  }
  

  namespace es.ull.patrones {
    namespace es.ull.patrones {
      namespace factory {
        class es.ull.patrones.factory.UNIXFactory {
            + createPipe()
            + createSocket()
            + createThread()
            + getNameOfFactory()
        }
      }
    }
  }
  

  namespace es.ull.patrones {
    namespace es.ull.patrones {
      namespace factory {
        class es.ull.patrones.factory.VMSFactory {
            + createPipe()
            + createSocket()
            + createThread()
            + getNameOfFactory()
        }
      }
    }
  }
  

  es.ull.patrones.factory.NTFactory .up.|> es.ull.patrones.factory.SystemFactory
  es.ull.patrones.factory.UNIXFactory .up.|> es.ull.patrones.factory.SystemFactory
  es.ull.patrones.factory.VMSFactory .up.|> es.ull.patrones.factory.SystemFactory


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
